name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

  workflow_dispatch:

jobs:

  build_webApi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebAPI
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6.X
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test with the dotnet CLI
        working-directory: ./WebAPI.Tests
        run: dotnet test
    