name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

  workflow_dispatch:

jobs:

  build_webApi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebAPI
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup .NET 6.X
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test with the dotnet CLI
        working-directory: ./WebAPI.Tests
        run: dotnet test

  build_react_App:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbilo-siuntos-frontend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hasFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Run Unit Tests
        run: yarn test --no-watch

      - name: Build
        run: yarn build

    